"""empty message

Revision ID: 34b053e0f63a
Revises: fd20edb87930
Create Date: 2021-11-07 20:00:40.359927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b053e0f63a'
down_revision = 'fd20edb87930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_navigations', sa.Column('b_block', sa.Boolean(), nullable=False, comment='блок'), schema='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cd_navigations', 'b_block', schema='admin')
    # ### end Alembic commands ###
