"""empty message

Revision ID: 403abbba96cb
Revises: 34b053e0f63a
Create Date: 2021-11-08 21:10:28.631300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403abbba96cb'
down_revision = '34b053e0f63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cd_navigations', 'b_block', schema='admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_navigations', sa.Column('b_block', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='блок'), schema='admin')
    # ### end Alembic commands ###
