"""empty message

Revision ID: 9d3fd76c8237
Revises: 2cca4eafc7ab
Create Date: 2021-11-06 16:02:08.437916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3fd76c8237'
down_revision = '2cca4eafc7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cd_persons', sa.Column('c_middle_name', sa.String(length=500), nullable=True, comment='имя'), schema='common')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cd_persons', 'c_middle_name', schema='common')
    # ### end Alembic commands ###
