"""empty message

Revision ID: fd20edb87930
Revises: 2cca4eafc7ab
Create Date: 2021-11-07 19:58:46.873531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd20edb87930'
down_revision = '2cca4eafc7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cd_navigations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='идентификатор'),
    sa.Column('c_title', sa.String(length=500), nullable=False, comment='название'),
    sa.Column('f_parent', postgresql.UUID(as_uuid=True), nullable=True, comment='родитель'),
    sa.Column('c_slug', sa.String(length=500), nullable=False, comment='псевдоним'),
    sa.Column('n_order', sa.Integer(), nullable=False, comment='порядок'),
    sa.ForeignKeyConstraint(['f_parent'], ['admin.cd_navigations.id'], ),
    sa.ForeignKeyConstraint(['id'], ['common.cd_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='admin',
    comment='меню'
    )
    op.add_column('cd_persons', sa.Column('d_birthdate', sa.Date(), nullable=False, comment='дата рождения'), schema='common')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cd_persons', 'd_birthdate', schema='common')
    op.drop_table('cd_navigations', schema='admin')
    # ### end Alembic commands ###
